#CARGANDO BASE DATOS

library(haven)
DATA_ECONR_BAS_SESION_4_EJEMPLO_1 <- read_dta("SESION 4/01-ARCHIVOS UTILIZADOS-DATA/DATA-ECONR-BAS-SESION 4-EJEMPLO 1.dta")
View((DATA_ECONR_BAS_SESION_4_EJEMPLO_1)

#CREANDO UNA NUEVA VARIABLE

DATA_ECONR_BAS_SESION_4_EJEMPLO_1$lwage = with(DATA_ECONR_BAS_SESION_4_EJEMPLO_1, log(wage))
View(DATA_ECONR_BAS_SESION_4_EJEMPLO_1)

DATA_ECONR_BAS_SESION_4_EJEMPLO_1$lwage

#ETIQUETANDO VARIABLE

library(Hmisc)
label(DATA_ECONR_BAS_SESION_4_EJEMPLO_1$lwage) = 'Logaritmo del salario por hora'

